  
name: Test
on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: '30 0 * * *'
jobs:
  game-of-life:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: current
    - name: Test
      run: |
        cd game-of-life
        npm install
        npm run asbuild
  i64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: current
    - name: Test
      run: |
        cd i64
        npm install
        npm run asbuild
        npm test
  interference:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: current
    - name: Test
      run: |
        cd interference
        npm install
        npm run asbuild
  libm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: current
    - name: Test
      run: |
        cd libm
        npm install
        npm run asbuild
        npm test
  loader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: current
    - name: Test
      run: |
        cd loader
        npm install
        npm run asbuild
        npm test
  mandelbrot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: current
    - name: Test
      run: |
        cd mandelbrot
        npm install
        npm run asbuild
  n-body:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: current
    - name: Test
      run: |
        cd n-body
        npm install
        npm run asbuild
      # npm test
  transform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: current
    - name: Test
      run: |
        cd transform
        npm install
        npm test
